import {CheckCircle2} from "lucide-react";
import SectionHeading from "@/components/ui/SectionHeading";
import ServiceCard from "@/components/ui/ServiceCard";
import LeadForm from "@/components/forms/LeadForm";
import CrossPromotion from "@/components/global/CrossPromotion";
export function AboutPage({type}:{type:"solar"|"construction"}){const solar=type==="solar";return <><section className={`inner-hero ${type}`}><div className="container"><span className="eyebrow">ABOUT {solar?"RAYBUILD SOLAR":"RAYBUILD CONSTRUCTION"}</span><h1>{solar?"About Raybuild Solar":"About Raybuild Construction"}</h1><p>{solar?"Welcome to Raybuild, your premier partner in sustainable green energy systems. Based in [Your City/Location], we assist residential clients, large scale commercial factories, and agricultural farms to pivot smoothly into sustainable solar operations.":"[VERIFIED COMPANY NARRATIVE — REPLACE FROM CLIENT]"}</p></div></section><section className="section"><div className="container two-col"><div><SectionHeading title="Our Approach"/><p className="prose">{solar?"At Raybuild Solar, our vision is to wipe out your carbon tax liabilities and drop monthly overhead grid power expenses to near zero. We assume full execution duties including customized structural designing, high-altitude heavy mechanical erections, earthing protections, and multi-year AMC maintenance plans. We build high-efficiency generation frameworks designed to last for generations.":"[ENGINEERING FOCUS AND VERIFIED COMPANY DETAILS]"}</p></div><div className="info-card"><h3>{solar?"Core Values":"Engineering Focus"}</h3><p>{solar?"Structural Safety · Live Tracking Help · Absolute Transparency":"[TEAM INFORMATION] · [CONSTRUCTION CAPABILITIES] · [VERIFIED DETAILS]"}</p></div></div></section><CrossPromotion active={type}/></>}
export function ServicesPage({type,services}:{type:"solar"|"construction",services:any[]}){return <><section className={`inner-hero ${type}`}><div className="container"><span className="eyebrow">RAYBUILD {type.toUpperCase()}</span><h1>Services</h1><p>Explore the specialized services delivered through this Raybuild division.</p></div></section><section className="section"><div className="container"><div className="service-grid">{services.map(s=><ServiceCard key={s.slug} service={s} base={`/${type}`}/>)}</div></div></section><CrossPromotion active={type}/></>}
export function ProjectsPage({type}:{type:"solar"|"construction"}){return <><section className={`inner-hero ${type}`}><div className="container"><span className="eyebrow">PORTFOLIO</span><h1>Projects</h1><p>Project portfolio architecture ready for verified Raybuild project information.</p></div></section><section className="section"><div className="container"><SectionHeading title="Project Portfolio" text="No project names, client names, locations, capacities or statistics are invented."/><div className="project-grid">{[1,2,3,4].map(n=><article className="project-card" key={n}><div>[PROJECT IMAGE]</div><h3>[PROJECT NAME]</h3><p>[LOCATION] · [PROJECT CATEGORY]</p><span>[PROJECT DESCRIPTION]</span></article>)}</div></div></section><CrossPromotion active={type}/></>}
export function ContactPage({type}:{type:"solar"|"construction"}){return <><section className={`inner-hero ${type}`}><div className="container"><span className="eyebrow">CONTACT RAYBUILD</span><h1>Let's discuss your requirement.</h1><p>Use the enquiry form or direct communication options below.</p></div></section><section className="section"><div className="container contact-grid"><div><SectionHeading title="Contact Information"/><div className="contact-list"><a href="tel:+91XXXXXXXXXX">[PRIMARY PHONE]</a><a href="mailto:[PRIMARY EMAIL]">[PRIMARY EMAIL]</a><a href="https://wa.me/91XXXXXXXXXX">[WHATSAPP NUMBER]</a><span>[COMPANY ADDRESS]</span><span>[BUSINESS HOURS]</span></div><div className="map-placeholder">[CLIENT GOOGLE MAPS LOCATION]</div></div><div className="inquiry-panel"><SectionHeading title="Send an Enquiry"/><LeadForm division={type}/></div></div></section><CrossPromotion active={type}/></>}
