"use client";
import {useState} from "react";
export default function LeadForm({division}:{division:"solar"|"construction"}){
 const solar=division==="solar"; const [error,setError]=useState(""); const [sent,setSent]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");const form=e.currentTarget;const data=Object.fromEntries(new FormData(form).entries());if(!/^[+]?[\d\s()-]{8,18}$/.test(String(data.contact_number||""))){setError("Please enter a valid contact number.");return}try{const r=await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...data,division})});if(!r.ok)throw new Error();setSent(true);form.reset()}catch{setError("We could not submit your enquiry. Please call or WhatsApp us.")}}
 if(sent)return <div className="success-box"><h3>Thank You!</h3><p>Your enquiry has been received. Our team will review your requirement and contact you shortly.</p><a className="btn btn-primary" href={`/${division}/thank-you`}>Continue</a></div>;
 const opts=solar?["Residential Rooftop","C&I Setup","Solar Pumps","Highmast Infrastructure"]:["New Construction","Repair & Retrofit","Waterproofing","Land Development","Plot Erection"];
 return <form className="lead-form" onSubmit={submit}><div className="form-grid"><label>Customer Name<input name="customer_name" required/></label><label>Contact Number<input name="contact_number" required inputMode="tel"/></label><label>{solar?"Location/City":"Project Site Location"}<input name="location" required/></label>{solar?<><label>Avg Monthly Bill (INR)<input name="monthly_bill" type="number" min="0" required/></label><label>Available Roof Space (Sq.Ft.)<input name="roof_space" type="number" min="0" required/></label></>:<label>Total Area / Plot Size (Sq.Ft.)<input name="project_area" type="number" min="0" required/></label>}<label className="full">{solar?"Service Choice":"Requirements"}<select name="service_type" required><option value="">Select</option>{opts.map(x=><option key={x}>{x}</option>)}</select></label></div>{error&&<p className="form-error" role="alert">{error}</p>}<button className="btn btn-primary" type="submit">Submit Enquiry</button></form>;
}
